@baseUrl = http://127.0.0.1:7001


# create admin
POST  {{baseUrl}}/superAdmin/createAdmin
Content-Type: application/json

{
  "username": "test",
  "phone": "18612875765",
  "password": "123456",
  "type": "web"
}
###

#get adminall
GET {{baseUrl}}/superAdmin/admin
###

#get admin
GET {{baseUrl}}/admin/2
###

#get admin
GET {{baseUrl}}/admin/type/web
###


#create tag

POST {{baseUrl}}/admin/createTag
Content-Type: application/json

{
  "adminId": 1,
  "title": "CSS"
}

###


#get tag all
GET {{baseUrl}}/tag/all
###

#get tag all
GET {{baseUrl}}/tag/2
###

#

GET {{baseUrl}}/tag/remove/1

###



#question all
GET {{baseUrl}}/question
###

#question all
GET {{baseUrl}}/question/1
###

#question create

POST {{baseUrl}}/question
Content-Type: application/json

{
  "title": "第三题"
}

###










#exam all

GET {{baseUrl}}/exam
###

#exam 

GET {{baseUrl}}/exam/11
###

#exam user

GET {{baseUrl}}/user/exam/5
###

#exam create

POST {{baseUrl}}/exam
Content-Type: application/json

{
  "id": 5,
  "title": "第一个试卷"
}

###


#exam find user

GET {{baseUrl}}/exam/user/3


###
 
#exam update

POST {{baseUrl}}/exam/update
Content-Type: application/json

{
  "id": 1,
  "title": "第1个试卷"
}


###










#user all

GET {{baseUrl}}/user

###

#user create

POST {{baseUrl}}/user
Content-Type: application/json

{
  "username": "zpk5",
  "phone": "18612875765",
  "age": 5,
  "sex": 1
}

###

#user update

POST {{baseUrl}}/user/update
Content-Type: application/json

{
  "id": 3,
  "username": "zpk333",
  "age": 33
}

###

#user update

PUT  {{baseUrl}}/user
Content-Type: application/json

{
  "id": 3,
  "username": "zpk3",
  "phone": "18612875765",
  "age": 3
}

###


#user del

DELETE  {{baseUrl}}/user/1


###


#user del

GET  {{baseUrl}}/user/del/2


###










# photo

GET {{baseUrl}}/photo

###



# photo

GET {{baseUrl}}/photo/36

###



# photo

POST {{baseUrl}}/photo
content-Type: application/json

{
  "name": "test3",
  "height": 111
}

###



# photo

DELETE  {{baseUrl}}/photo/32

###













# @name login
POST {{baseUrl}}/api/login HTTP/1.1
Content-Type: application/x-www-form-urlencoded

name=foo&password=bar

###

@authToken = {{login.response.headers.X-AuthToken}}

# @name createComment
POST {{baseUrl}}/comments HTTP/1.1
Authorization: {{authToken}}
Content-Type: application/json

{
    "content": "fake content"
}

###

@commentId = {{createComment.response.body.$.id}}

# @name getCreatedComment
GET {{baseUrl}}/comments/{{commentId}} HTTP/1.1
Authorization: {{authToken}}

###

# @name getReplies
GET {{baseUrl}}/comments/{{commentId}}/replies HTTP/1.1
Accept: application/xml

###

# @name getFirstReply
GET {{baseUrl}}/comments/{{commentId}}/replies/{{getReplies.response.body.//reply[1]/@id}}